User:
  name: Aquiles

ZMQ:
  port: 5555

DAQ:
  model: Real # Dummy
  port: 'ASRL/dev/cu.usbmodem11201::INSTR'

Camera:
  number: 0

Scan:
  channel_in: 0
  channel_out: 0
  start: 0
  stop: 3.3
  step: 0.01
  delay: 0.5  # In seconds

Data:
  saving_folder: /Users/aquiles/Data
  filename: scan.h5
  movie_filename: movie.h5